osx_image: xcode7.1
language: objective-c

before_install:
- rvm use $RVM_RUBY_VERSION
- brew update
- brew outdated xctool || brew upgrade xctool

install: 
- bundle install --without=documentation --path ../travis_bundle_dir

script: 
- xctool clean build -project SwiftCop.xcodeproj -scheme SwiftCop -sdk iphonesimulator
- ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)