osx_image: xcode7.1
language: objective-c

before_install:
- brew update || brew update
- brew outdated xctool || brew upgrade xctool

script: 
- xctool clean build -project SwiftCop.xcodeproj -scheme SwiftCop -sdk iphonesimulator
- ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
