osx_image: xcode7.1
language: objective-c

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project SwiftCop.xcodeproj -scheme SwiftCop -sdk iphonesimulator
- xctool test -project SwiftCop.xcodeproj -scheme SwiftCop -sdk iphonesimulator